<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../Assets/Scripts/Core/**/*.cs" Link="Core/%(RecursiveDir)%(Filename)%(Extension)" />
    <Compile Include="../../Assets/Scripts/Game/Evolution/CharacterEvolutionJsonImporter.cs" Link="Game/Evolution/CharacterEvolutionJsonImporter.cs" />
    <Compile Include="../../Assets/Scripts/Game/Evolution/CharacterEvolutionRequestJsonExporter.cs" Link="Game/Evolution/CharacterEvolutionRequestJsonExporter.cs" />
  </ItemGroup>
</Project>
